spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: sunyoring
    password: sunyoring

# yml방식이란 ? -  springBoot는 xml이 아니라 yml에 프로젝트에 관한 모든 설정을 적는다. 중복 작성되는 부분이 적고 xml 방식이나 properties 보다 편리하다. 